project:
  type: book
  output-dir: ../docs
  execute-dir: project

book:
  title: "Extended Analysis of Provincial Funding for Social Services in Ontario"
  subtitle: "Data Analysis Reporting"
  author: "Thomas McManus"
  date: "2024-07-26"
  chapters:
    - index.qmd
    - york-replication.qmd
  favicon: favicon.png
  sidebar:
    logo: blueprint-logo.png

bibliography: refs.bib

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    code-fold: true
    code-summary: "Show code"
  typst:
    execute:
      echo: false

knitr:
  opts_chunk:
    dev: "ragg_png"

execute: 
  cache: false
  message: false
  warning: false


